newsite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("shop.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
]

shop/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", views.home, name="home"),
    path("search", views.search, name="search"),
    path("categories", views.category_list, name="categories"),
    path("brands", views.brand_list, name="brands"),
    path("products", views.product_list, name="products"),
    path("categories_product/<int:cat_id>", views.category_product_list, name="categories_product"),
    path("brands_product/<int:brand_id>", views.brand_product_list, name="brands_product"),
    path("product/<str:slug>/<int:id>", views.product_detail, name="product_detail"),
    path("filter-data", views.filter_data, name="filter_data"),
    path("load-more-data", views.load_more_data, name="load_more_data"),
    path("add-to-cart", views.add_to_cart, name="add_to_cart"),
    path("cart", views.cart_list, name="cart"),
    path("delete-from-cart", views.delete_cart_item, name="delete-from-cart"),
    path("update-cart", views.update_cart_item, name="update-cart"),
    path("accounts/signup", views.signup, name="signup"),
    path("save-review/<int:pid>", views.save_review, name="save-review"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from django.utils.html import mark_safe
from django.contrib.auth.models import User

#Баннеры
class Banneer(models.Model):
    image=models.ImageField(upload_to='banner_img/')
    alt_text=models.CharField(max_length=300)

    def image_tag(self):
        return mark_safe('<img src="%s" width="100" />' % (self.image.url))

    def __str__(self):
        return self.alt_text

    class Meta:
        verbose_name = '1. Баннеры'
        verbose_name_plural = '1. Баннеры'

class Category(models.Model):
    title=models.CharField(max_length=100)
    image=models.ImageField(upload_to='cat_img/')

    def __str__(self):
        return self.title

    def image_tag(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))

    class Meta:
        verbose_name = '2. Категории'
        verbose_name_plural = '2. Категории'

class Brand(models.Model):
    title=models.CharField(max_length=100)
    image=models.ImageField(upload_to='brand_img/')

    def __str__(self):
        return self.title

    def image_tag(self):
        return mark_safe('<img src="%s" width="60" height="60" />' % (self.image.url))

    class Meta:
        verbose_name = '3. Мерч'
        verbose_name_plural = '3. Мерч'



#Размер товара
class Size(models.Model):
    title=models.CharField(max_length=100)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '4. Размеры'
        verbose_name_plural = '4. Размеры'

#Товары
class Product(models.Model):
    title=models.CharField(max_length=200)
    slug = models.CharField(max_length=400)
    detail = models.TextField()
    specs = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    size = models.ForeignKey(Size, on_delete=models.CASCADE)
    status = models.BooleanField(default=True)
    is_featured = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '5. Товары'
        verbose_name_plural = '5. Товары'

#Атрибуты товаров
class ProductAttribute(models.Model):
    product=models.ForeignKey(Product, on_delete=models.CASCADE)
    size = models.ForeignKey(Size, on_delete=models.CASCADE)
    price = models.PositiveIntegerField(default=0)
    image = models.ImageField(upload_to='prod_imgs/', null=True)

    def __str__(self):
        return self.product.title

    class Meta:
        verbose_name = '6. Атрибуты товаров'
        verbose_name_plural = '6. Атрибуты товаров'

    def image_tag(self):
        return mark_safe('<img src="%s" width="60" height="60" />' % (self.image.url))

# # Заказы
# class CartOrder(models.Model):
#     user=models.ForeignKey(User, on_delete=models.CASCADE)
#     total_amt = models.FloatField()
#     paid_status=models.BooleanField(default=False)
#     order_dt=models.DateField(auto_now_add=True)
#
#     def __str__(self):
#         return self.user
#
#     class Meta:
#         verbose_name = '7. Заказы'
#         verbose_name_plural = '7. Заказы'
#
#
# #Детали заказа
# class CartOrderItems(models.Model):
#     order=models.ForeignKey(CartOrder, on_delete=models.CASCADE)
#     invoice_no=models.CharField(max_length=150)
#     item = models.CharField(max_length=150)
#     image = models.CharField(max_length=200)
#     qty = models.IntegerField()
#     price = models.FloatField()
#     total = models.FloatField()
#
#     def __str__(self):
#         return self.order
#
#     class Meta:
#         verbose_name = '8. Детали заказа'
#         verbose_name_plural = '8. Детали заказа'

# Отзыв товара
RATING=(
    (1,'1'),
    (2,'2'),
    (3,'3'),
    (4,'4'),
    (5,'5'),
)
class ProductReview(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    review_text=models.TextField()
    review_rating=models.CharField(choices=RATING,max_length=150)

    def get_review_rating(self):
        return self.review_rating

    class Meta:
        verbose_name = '#. Оценки товаров'
        verbose_name_plural = '#. Оценки товаров'

shop/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import ProductReview

class SignupForm(UserCreationForm):
    full_names = forms.CharField(max_length=50,required=True)
    mobile = forms.CharField(widget=forms.TextInput(attrs={'type':'number'}))
    address = forms.CharField(max_length=50, required=True)

    class Meta:
        model = User
        fields=('full_names','mobile', 'address', 'username', 'password1', 'password2')

class ReviewAdd(forms.ModelForm):
    class Meta:
        model=ProductReview
        fields=('review_text','review_rating')

shop/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse,HttpResponse
from django.template.loader import render_to_string
from django.db.models import Min,Max,Count,Avg
from .models import *
from .forms import SignupForm,ReviewAdd
from django.contrib.auth import login,authenticate

# Домашняя страница
def home(request):
    banners = Banneer.objects.all().order_by('-id')
    data = Product.objects.filter(is_featured=True).order_by('id')
    return render(request, 'index.html', {'data': data, 'banners': banners})

#Категории
def category_list(request):
    data = Category.objects.all().order_by('-id')
    return render(request, 'category_list.html', {'data': data})

#Бренды
def brand_list(request):
    data = Brand.objects.all().order_by('-id')
    return render(request, 'brand_list.html', {'data': data})

#Список товаров
def product_list(request):
    total_data=Product.objects.count()
    data = Product.objects.all().order_by('-id')[:3]
    min_price=ProductAttribute.objects.aggregate(Min('price'))
    max_price = ProductAttribute.objects.aggregate(Max('price'))
    return render(request, 'product_list.html',
        {
            'data': data,
            'total_data':total_data,
            'min_price':min_price,
            'max_price': max_price,
        }
        )

#Список товаров по категориям
def category_product_list(request,cat_id):
    category=Category.objects.get(id=cat_id)
    data=Product.objects.filter(category=category).order_by('-id')
    return render(request, 'category_product_list.html', {
            'data': data,
            })

#Список товаров по брендам
def brand_product_list(request,brand_id):
    brand=Brand.objects.get(id=brand_id)
    data=Product.objects.filter(brand=brand).order_by('-id')
    return render(request, 'brand_product_list.html', {
            'data': data,
            })

# Детали товара
def product_detail(request, slug, id):
    product=Product.objects.get(id=id)
    related_produtcs = Product.objects.filter(category=product.category).exclude(id=id)[:4]
    sizes = ProductAttribute.objects.filter(product=product).values('size__id','size__title','price').distinct()
    reviewForm=ReviewAdd()

    #Проверка на добавление отзыва
    canAdd=True
    reviewCheck=ProductReview.objects.filter(user=request.user, product=product).count()
    if request.user.is_authenticated:
        if reviewCheck > 0:
            canAdd=False

    # Отображение отзывов
    reviews=ProductReview.objects.filter(product=product)
    # Средняя оценка
    avg_reviews = ProductReview.objects.filter(product=product).aggregate(avg_rating=Avg('review_rating'))

    return render(request, 'product_detail.html', {'data':product, 'related':related_produtcs,'sizes':sizes, 'reviewForm': reviewForm, 'canAdd': canAdd, 'reviews': reviews, 'avg_reviews': avg_reviews})

# Функция Поиска
def search(request):
    q=request.GET['q']
    data = Product.objects.filter(title__icontains=q).order_by('-id')
    return render(request, 'search.html', {'data': data})

# Данные фильтра
def filter_data(request):
    categories = request.GET.getlist('category[]')
    brands = request.GET.getlist('brand[]')
    sizes = request.GET.getlist('size[]')
    minPrice = request.GET['minPrice']
    maxPrice = request.GET['maxPrice']
    allProducts = Product.objects.all().order_by('-id').distinct()
    allProducts = allProducts.filter(productattribute__price__gte=minPrice)
    allProducts = allProducts.filter(productattribute__price__lte=maxPrice)
    if len(categories)>0:
        allProducts=allProducts.filter(category__id__in=categories).distinct()
    if len(brands)>0:
        allProducts=allProducts.filter(brand__id__in=brands).distinct()
    if len(sizes)>0:
        allProducts=allProducts.filter(productattribute__size__id__in=sizes).distinct()
    t = render_to_string('ajax/product-list.html', {'data':allProducts})
    return JsonResponse(({'data':t}))

# Показать больше
def load_more_data(request):
    offset = int(request.GET['offset'])
    limit = int(request.GET['limit'])
    data = Product.objects.all().order_by('-id')[offset:offset+limit]
    t = render_to_string('ajax/product-list.html', {'data': data})
    return JsonResponse(({'data': t}))

# Добавление в корзину
def add_to_cart(request):
    #del request.session['cartdata']
    cart_p={}
    cart_p[str(request.GET['id'])]={
        'image': request.GET['image'],
        'title':request.GET['title'],
        'qty': request.GET['qty'],
        'price': request.GET['price'],
    }
    if 'cartdata' in request.session:
        if str(request.GET['id']) in request.session['cartdata']:
            cart_data=request.session['cartdata']
            cart_data[str(request.GET['id'])]['qty']=int(cart_p[str(request.GET['id'])]['qty'])
            cart_data.update(cart_data)
            request.session['cartdata']=cart_data
        else:
            cart_data = request.session['cartdata']
            cart_data.update(cart_p)
            request.session['cartdata'] = cart_data
    else:
        request.session['cartdata']=cart_p
    return JsonResponse({'data':request.session['cartdata'],'totalitems':len(request.session['cartdata'])})


# Корзина
def cart_list(request):
    total_amt=0
    for p_id, item in request.session['cartdata'].items():
        total_amt+=int(item['qty'])*float(item['price'])
    return render(request, 'cart.html', {'cart_data':request.session['cartdata'],'totalitems':len(request.session['cartdata']),'total_amt':total_amt})

# Удаление из корзины
def delete_cart_item(request):
    p_id=str(request.GET['id'])
    if 'cartdata' in request.session:
        if p_id in request.session['cartdata']:
            cart_data = request.session['cartdata']
            del request.session['cartdata'][p_id]
            request.session['cartdata']=cart_data
    total_amt = 0
    for p_id, item in request.session['cartdata'].items():
        total_amt += int(item['qty']) * float(item['price'])
    t = render_to_string('ajax/cart-list.html',{'cart_data':request.session['cartdata'],'totalitems':len(request.session['cartdata']),'total_amt':total_amt})
    return JsonResponse({'data': t,'totalitems':len(request.session['cartdata'])})

# Обновление корзины
def update_cart_item(request):
    p_id=str(request.GET['id'])
    p_qty=request.GET['qty']
    if 'cartdata' in request.session:
        if p_id in request.session['cartdata']:
            cart_data = request.session['cartdata']
            cart_data[str(request.GET['id'])]['qty']=p_qty
            request.session['cartdata']=cart_data
    total_amt = 0
    for p_id, item in request.session['cartdata'].items():
        total_amt += int(item['qty']) * float(item['price'])
    t = render_to_string('ajax/cart-list.html',{'cart_data':request.session['cartdata'],'totalitems':len(request.session['cartdata']),'total_amt':total_amt})
    return JsonResponse({'data': t,'totalitems':len(request.session['cartdata'])})

# Регистрация
def signup(request):
    if request.method=='POST':
        form=SignupForm(request.POST)
        if form.is_valid():
            form.save()
            username=form.cleaned_data.get('username')
            pwd=form.cleaned_data.get('password1')
            user=authenticate(username=username,password=pwd)
            login(request,user)
            return redirect('home')
    form=SignupForm
    return render(request, 'registration/signup.html', {'form': form})

#Сохранение отзыва
def save_review(request,pid):
    product=Product.objects.get(pk=pid)
    user=request.user
    review=ProductReview.objects.create(
        user=user,
        product=product,
        review_text=request.POST['review_text'],
        review_rating=request.POST['review_rating'],
        )
    data ={
        'user': user.username,
        'review_text': request.POST['review_text'],
        'review_rating': request.POST['review_rating']
    }

    avg_reviews = ProductReview.objects.filter(product=product).aggregate(avg_rating=Avg('review_rating'))

    return JsonResponse({'bool':True, 'data': data, 'avg_reviews':avg_reviews})

shop/templates/brand_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<!-- Featured Products -->
	<h3 class="my-4 border-bottom pb-1">Мерч</h3>
	<div class="row">
		{% if data %}
			{% for brand in data %}
			<div class="col-md-3 mb-4">
				<div class="card shadow">
				  <a href="/brands_product/{{brand.id}}"><img src="/media/{{brand.image}}" class="card-img-top" alt="{{brand.title}}"
				  ></a>
				  <div class="card-body">
					  <h6 class="card-text"><a href="/brands_product/{{brand.id}}">{{brand.title}}</a></h6>
				  </div>
				</div>
			</div>
			{% endfor %}
		{% endif %}
	</div>
</main>
{% endblock %}

shop/templates/brand_product_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<div class="row">
		<!-- Filters -->
		<div class="col-md-3">
			{% include 'filters.html' %}
		</div>
		<div class="col-md-9">
			<!-- Products -->
			<h3 class="mb-4 border-bottom pb-1">
				Товары
			</h3>
			<div class="row" id='filteredProducts'>
				<p class="ajaxLoader">Загрузка...</p>
				{% for product in data %}
				<div class="col-lg-4 col-md-6 mb-4 product-box">
					<div class="card shadow">
					  <a href="/product/{{product.slug}}/{{product.id}}"><img src="/media/{{product.productattribute_set.first.image}}" class="card-img-top" alt="{{product.title}}"></a>
					  <div class="card-body">
					    <h5 class="card-text"><a href="/product/{{product.slug}}/{{product.id}}">{{product.title}}</a></h5>
						<h6><span class="product-price-{{product.id}}">{{product.productattribute_set.first.price}}</span> ₽</h6>
					  </div>
					  <div class="card-footer">
						<input type="hidden" value="1" class="form-control product-qty-{{product.id}}" id="productQty" />
						<input type="hidden" class="product-image-{{product.id}}" value="{{product.productattribute_set.first.image}}">
						<input type="hidden" class="product-id-{{product.id}}" value="{{product.id}}">
						<input type="hidden" class="product-title-{{product.id}}" value="{{product.title}}">
						  	<button class="btn btn-sm btn-primary add-to-cart" data-index="{{product.id}}"><i class="fa fa-shopping-cart"></i></button>
							<button class="btn btn-sm btn-danger"><i class="fa fa-heart"></i></button>
							<span class="float-right">
								4.5/5
								<i class="fa fa-star text-warning"></i>
							</span>
					  </div>
					</div>
				</div>
				{% endfor %}
			</div>
		</div>
	</div>
</main>
{% endblock %}

shop/templates/category_product_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<div class="row">
		<!-- Filters -->
		<div class="col-md-3">
			{% include 'filters.html' %}
		</div>
		<div class="col-md-9">
			<!-- Products -->
			<h3 class="mb-4 border-bottom pb-1">
				Товары
			</h3>
			<div class="row" id='filteredProducts'>
				<p class="ajaxLoader">Загрузка...</p>
				{% for product in data %}
				<div class="col-lg-4 col-md-6 mb-4 product-box">
					<div class="card shadow">
					  <a href="/product/{{product.slug}}/{{product.id}}"><img src="/media/{{product.productattribute_set.first.image}}" class="card-img-top" alt="{{product.title}}"></a>
					  <div class="card-body">
					    <h5 class="card-text"><a href="/product/{{product.slug}}/{{product.id}}">{{product.title}}</a></h5>
						<h6><span class="product-price-{{product.id}}">{{product.productattribute_set.first.price}}</span> ₽</h6>
					  </div>
					  <div class="card-footer">
						<input type="hidden" value="1" class="form-control product-qty-{{product.id}}" id="productQty" />
						<input type="hidden" class="product-image-{{product.id}}" value="{{product.productattribute_set.first.image}}">
						<input type="hidden" class="product-id-{{product.id}}" value="{{product.id}}">
						<input type="hidden" class="product-title-{{product.id}}" value="{{product.title}}">
						  	<button class="btn btn-sm btn-primary add-to-cart" data-index="{{product.id}}"><i class="fa fa-shopping-cart"></i></button>
							<button class="btn btn-sm btn-danger"><i class="fa fa-heart"></i></button>
							<span class="float-right">
								4.5/5
								<i class="fa fa-star text-warning"></i>
							</span>
					  </div>
					</div>
				</div>
				{% endfor %}
			</div>
		</div>
	</div>
</main>
{% endblock %}

shop/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- ползунок главной стр -->
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    {% for banners in banners %}
    {% if forloop.counter == 1 %}
    <li data-target="#carouselExampleIndicators" data-slide-to="{{forloop.counter}}" class="active"></li>
    {% else %}
    <li data-target="#carouselExampleIndicators" data-slide-to="{{forloop.counter}}"></li>
    {% endif %}
    {% endfor %}
  </ol>
  <div class="carousel-inner">
    {% for banner in banners %}
    {% if forloop.counter == 1 %}
    <div class="carousel-item active">
      {% else %}
      <div class="carousel-item">
      {% endif %}
      <img src="/media/{{banner.image}}" class="d-block w-100" alt="...">
    </div>
    {% endfor %}
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<main class="container my-4">
	<!-- Рекомендуемые товары -->
	<h3 class="my-4 border-bottom pb-1">Рекомендуемые товары</h3>
	<div class="row">
        {% for product in data %}
		<div class="col-md-3 mb-4">
			<div class="card shadow">
			  <a href="/product/{{product.slug}}/{{product.id}}"><img src="/media/{{product.productattribute_set.first.image}}" class="card-img-top" alt="{{product.title}}"></a>
			  <div class="card-body">
			    <h5 class="card-text"><a href="/product/{{product.slug}}/{{product.id}}">{{product.title}}</a></h5>
                <h6><span class="product-price-{{product.id}}">{{product.productattribute_set.first.price}}</span> ₽</h6>
			  </div>
			  <div class="card-footer">
                <input type="hidden" value="1" class="form-control product-qty-{{product.id}}" id="productQty" />
                <input type="hidden" class="product-image-{{product.id}}" value="{{product.productattribute_set.first.image}}">
				<input type="hidden" class="product-id-{{product.id}}" value="{{product.id}}">
				<input type="hidden" class="product-title-{{product.id}}" value="{{product.title}}">
			  	<button class="btn btn-sm btn-primary add-to-cart" data-index="{{product.id}}"><i class="fa fa-shopping-cart"></i></button>
			  	<button class="btn btn-sm btn-danger"><i class="fa fa-heart"></i></button>
			  	<span class="float-right">
			  		4.5/5
			  		<i class="fa fa-star text-warning"></i>
			  	</span>
			  </div>
			</div>
		</div>
        {% endfor %}
	</div>
	<p class="my-4 text-center"><a href="{% url 'products' %}" class="btn btn-dark btn-sm">Все товары <i class="fa fa-long-arrow-alt-right"></i></a></p>
</main>
{% endblock %}

shop/templates/product_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<!-- Featured Products -->
	<h3 class="my-4 border-bottom pb-1">{{data.title}}</h3>
	<div class="row">
		<!-- Images -->
		<div class="col-md-4">
			<img id="zoom_01" data-zoom-image="/media/{{data.productattribute_set.first.image}}" src="/media/{{data.productattribute_set.first.image}}" class="card-img-top" alt="{{data.title}}">
		</div>
		<div class="col-md-8">
			<p>{{data.detail}}</p>
			<hr/>
			<table class="table table-bordered">
				<tr>
					<th>Цена</th>
					<th><span class="product-price-{{data.id}}">{{data.productattribute_set.first.price}}</span> ₽</th>
				</tr>
				<tr>
					<th>Размеры</th>
					<td>
                        {% for size in sizes %}
						<button data-price="{{size.price}}" class="btn btn-outline-secondary btn-sm choose-size">{{size.size__title}}</button>
						{% endfor %}
					</td>
				</tr>
			</table>
			<hr/>
			<div class="input-group my-3" style="width:30%;">
			  <input type="number" value="1" class="form-control product-qty-{{data.id}}" id="productQty" />
			  <div class="input-group-append">
				<input type="hidden" class="product-image-{{data.id}}" value="{{data.productattribute_set.first.image}}">
				  <input type="hidden" class="product-id-{{data.id}}" value="{{data.id}}">
				  <input type="hidden" class="product-title-{{data.id}}" value="{{data.title}}">
			    <button class="btn btn-primary btn-sm add-to-cart" data-index="{{data.id}}" type="button" id="addToCartBtn"><i class="fa fa-shopping-cart"></i> В корзину</button>
			  </div>
			</div>
		</div>
	</div>
	<hr />
	<div class="row">
		<div class="col-md-6">
			<h3 class="my-3">Детали</h3>
			<!-- Detail -->
			<table class="table table-bordered">
				<tr>
					<th>Мерч</th>
					<td><a href="#">{{data.brand.title}}</a></td>
				</tr>
				<tr>
					<th>Категория</th>
					<td><a href="#">{{data.category.title}}</a></td>
				</tr>
				<tr>
					<th>Спецификация</th>
					<td>{{data.specs}}</td>
				</tr>
			</table>
		</div>
		<!-- Reviews -->
		<div class="col-md-6">
			<h3 class="my-3">Оценка товара - <span class="avg-rating">{{avg_reviews.avg_rating}}</span>/5 <i class="fa fa-star text-warning"></i>
				{% if user.is_authenticated %}
				{% if canAdd %}
				<button data-toggle="modal" data-target="#productReview" type="button" class="btn btn-warning btn-sm float-right reviewBtn">Оставить отзыв</button>
				{% endif %}
				{% endif %}
			</h3>
	{% if user.is_authenticated %}
	<!-- Отзыв о товаре -->
	<div class="modal fade" id="productReview" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
	  <div class="modal-dialog">
		<div class="modal-content">
		  <div class="modal-header">
			<h5 class="modal-title" id="exampleModalLabel">Ваш отзыв о товаре</h5>
			<button type="button" class="close" data-dismiss="modal" aria-label="Close">
			  <span aria-hidden="true">&times;</span>
			</button>
		  </div>
		  <div class="modal-body">
			<form method="post" id="addForm" action="{% url 'save-review' data.id %}">
				{% csrf_token %}
				<table class="table table-bordered">
					{{reviewForm.as_table}}
					<tr>
						<td colspan="2">
							<button type="submit" class="btn btn-primary">Отправить</button>
							<input type="reset" value="Сбросить" id="reset" />
						</td>
					</tr>
				</table>
				<p class="ajaxRes"></p>
		  </form>
		  </div>
		</div>
	  </div>
	</div>
	<!-- Отзыв о товаре -->
	{% endif %}
			</h3>
			<div class="card">
				<div class="card-body review-list" style="max-height: 400px; overflow: auto;">
					<!-- Detail -->
					{% for review in reviews %}
					<blockquote class="blockquote text-right">
					  <small>{{review.review_text}}</small>
					  <footer class="blockquote-footer">{{review.user}}
					  	<cite title="Source Title">
							{% for star in review.review_rating|ljust:review.review_rating %}
					  		<i class="fa fa-star text-warning"></i>
							{% endfor %}
					  	</cite>
					  </footer>
					</blockquote>
					<hr />
					{% endfor %}
				</div>
			</div>
		</div>
	</div>
	<!-- ПОХОЖИЕ ТОВАРЫ -->
	<h3 class="mt-4 mb-3 border-bottom pb-1">Похожие товары</h3>
	<div class='row'>
		{% for product in related %}
				<div class="col-md-3 mb-4">
					<div class="card shadow">
					  <a href="/product/{{product.slug}}/{{product.id}}"><img src="/media/{{product.productattribute_set.first.image}}" class="card-img-top" alt="{{product.title}}"></a>
					  <div class="card-body">
					    <h5 class="card-text"><a href="/product/{{product.slug}}/{{product.id}}">{{product.title}}</a></h5>
						<h6><span class="product-price-{{product.id}}">{{product.productattribute_set.first.price}}</span> ₽</h6>
					  </div>
					  <div class="card-footer">
						<input type="hidden" value="1" class="form-control product-qty-{{product.id}}" id="productQty" />
						<input type="hidden" class="product-image-{{product.id}}" value="{{product.productattribute_set.first.image}}">
						<input type="hidden" class="product-id-{{product.id}}" value="{{product.id}}">
						<input type="hidden" class="product-title-{{product.id}}" value="{{product.title}}">
						  	<button class="btn btn-sm btn-primary add-to-cart" data-index="{{product.id}}"><i class="fa fa-shopping-cart"></i></button>
							<button class="btn btn-sm btn-danger"><i class="fa fa-heart"></i></button>
							<span class="float-right">
								4.5/5
								<i class="fa fa-star text-warning"></i>
							</span>
					  </div>
					</div>
				</div>
		{% endfor %}
	</div>
</main>
<script src="https://cdn.jsdelivr.net/gh/igorlino/elevatezoom-plus@1.2.3/src/jquery.ez-plus.js"></script>
<script>
    $('#zoom_01').ezPlus();
</script>
{% endblock %}